### ISSUE TITLE
Can't bring up media bar/controls

### ISSUE THREAD

**Issue by WolfRamAlpha12** [bmlzootown/Hydravion#13]
As the title states, can't bring up media bar/controls once they disappear after inactivity at the start of the video. While the controls are up, I can navigate and use the functions and scrobble through the video just fine, but after it disappears I can't bring them up again. 

There is only the DPad and select button to interact with foreground apps on the remote, so I'm at a loss on how else I'd bring up the control banner. Do let me know if I'm missing something obvious or if I can provide more information

Device: Chromecast with Google TV
Android TV version: 10
Running the latest version, sideloaded.

**Comment by bmlzootown** [comment]
Should be fixed as of the latest version (v1.1.0). If it's still misbehaving, or you have any other issues, feel free to re-open [**_this_**](https://github.com/bmlzootown/Hydravion-AndroidTV/issues/1) issue.
